#!/bin/sh

# The name of the module file you want to load into the kernel. It is determined by the Makefile which compiles this module file.
# This name will be shown inside /proc/modules file or when using the command lsmod.
DRV_MODULE_0="pib_pcie_hpif"
DRV_MODULE_1="pib_pcie_lwif"
# The name of driver you put into the kernel. It is defined in alt_up_pci_driver.h.
# This name can be found inside /proc/devices file
DRV_NAME_0="pib_pcie_hpif"
DRV_NAME_1="pib_pcie_lwif"
# The default name of the configuration file.
CONFIG_FILE_0="config_file_0"
CONFIG_FILE_1="config_file_1"
# This will enable the file to be read and written by everyone.
DRV_MODE="666"

# Group: since distributions have different group-policy,
# look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
	DRV_GROUP="staff"
else
	DRV_GROUP="wheel"
fi

# invoke insmod with the information extracted from the configuration file
/sbin/insmod ./${DRV_MODULE_0}.ko `awk '$1!~/^#/' $CONFIG_FILE_0 | tr -d " " | tr -d "\t" | tr "\n" " "` ||  exit 1

# get the major number of the device if the probe() is called successfully by the kernel
DRV_MAJOR=`cat /proc/devices | grep $DRV_NAME_0 | awk '{print $1}' `

# check whether the driver get a major number for cdev or not
if [ -n "$DRV_MAJOR" ]; then
	echo PCIe HPIF Device Found
else
	echo PCIe HPIF Device Not Found
	sh unload 0
	exit 1
fi

# set appropriate group and permission
chgrp $DRV_GROUP /dev/$DRV_NAME_0*
chmod $DRV_MODE  /dev/$DRV_NAME_0*

# invoke insmod with the information extracted from the configuration file
/sbin/insmod ./${DRV_MODULE_1}.ko `awk '$1!~/^#/' $CONFIG_FILE_1 | tr -d " " | tr -d "\t" | tr "\n" " "` ||  exit 1

# get the major number of the device if the probe() is called successfully by the kernel
DRV_MAJOR=`cat /proc/devices | grep $DRV_NAME_1 | awk '{print $1}' `

# check whether the driver get a major number for cdev or not
if [ -n "$DRV_MAJOR" ]; then
	echo PCIe LWIF Device Found
else
	echo PCIe LWIF Device Not Found
	sh unload 1
	exit 1
fi

# set appropriate group and permission
chgrp $DRV_GROUP /dev/$DRV_NAME_1*
chmod $DRV_MODE  /dev/$DRV_NAME_1*

